### ISSUE TITLE
Animating the welcome message:

### ISSUE THREAD

**Issue by feherszabolcs** [feherszabolcs/portfolio#1]
```css
.welcome-message h2 {
    color: #fff;
    font-size: 8em;
    position: absolute;
    transform: translate(-50%, -50%);
  }
  
  .welcome-message h2:nth-child(1) {
    color: transparent;
    -webkit-text-stroke: 2px #03a9f4;
  }
  
  .welcome-message h2:nth-child(2) {
    color: #03a9f4;
    animation: animate 4s ease-in-out infinite;
  }

 @keyframes animate {
    0%,
    100% {
      clip-path: polygon(
        0% 45%,
        16% 44%,
        33% 50%,
        54% 60%,
        70% 61%,
        84% 59%,
        100% 52%,
        100% 100%,
        0% 100%
      );
    }
  
    50% {
      clip-path: polygon(
        0% 60%,
        15% 65%,
        34% 66%,
        51% 62%,
        67% 50%,
        84% 45%,
        100% 46%,
        100% 100%,
        0% 100%
      );
    }
  }
/*this to the welcome.css to add waving effect to the text*/
```
also remove footer's fixed position from `App.css`

replace current text in the jsx to this: 
```html
                <h1>Welcome</h1>
                <h1>Welcome</h1>
```
